name: Go Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install Dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run Tests
      run: go test -v ./...

    - name: Set Build Status
      if: always()
      uses: juliogallegos/github-status-action@v1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: ${{ job.status }}
        description: ${{ job.status }}
