name: goreleaser

# on: [push]
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
      -
        name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Tests
        run: go test -v ./...
      -
        name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      # -
      #   name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v4
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Push a package to Octopus Deploy 🐙
      #   uses: OctopusDeploy/push-package-action@v3
      #   env:
      #     OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
      #     OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      #     OCTOPUS_SPACE: 'Default'
      #   with:
      #     packages: |
      #       dist/hcledit_Linux_x86_64.tar.gz
      #
      # - name: Push build information to Octopus Deploy 🐙
      #   uses: OctopusDeploy/push-build-information-action@v3
      #   env:
      #     OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
      #     OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      #     OCTOPUS_SPACE: '<spacename>'
      #   with:
      #     packages: |
      #       '<packageId1>'
      #     version: '<versionofpackages>'

